name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run vcpkg
      uses: lukka/run-vcpkg@v4
      with:
        vcpkgArguments: 'install openssl-windows:x64-windows'
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'

    - name: Run vcpkg
      uses: lukka/run-vcpkg@v4
      with:
        vcpkgArguments: 'integrate install'
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
    - name: Build
      run: cargo build --release

    - name: Upload Release Target
      uses: actions/upload-artifact@v4
      with:
        name: Release Target
        path: target/release